# Conclusion {#conclusion}

We live in an ageing world, where people aged 60 or over will be 2 billion or about 22% of the world's population by 2050.

Currently, two in three people aged 60 years or older live in developing countries. By 2050, nearly four in five older people will be living in the developing world.

The changing demographics of ageing combined with the increasing number of disasters will exert a disproportionate impact on the world’s oldest and poorest.

In this context, identifying the needs of older people as accurately as possible is a necessity. More and more donors and UN agencies are now willing to include older people in their programmes. Age markers, to complement gender markers, will be disseminated very soon

RAM-OP is offering a fast, robust, reliable, tested and user-friendly way of assessing the needs of older people. It can be used in humanitarian situations as well as in development contexts. The modular structure of RAM-OP allows for adaptations, making it exhaustive or limited to essential indicators according to the immediate needs.

As more organisations start to use it, RAM-OP will evolve and improve. New versions of RAM-OP can be created (for example, RAM-OP for refugee or displaced people camps). We wish that a greater number of actors will start using RAM-OP and make it their own.